# Generated by Django 4.2 on 2023-04-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentdone',
            field=models.CharField(choices=[('1', 'COMPLETED'), ('2', 'PENDING')], default='1', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('1', 'COMPLETED'), ('2', 'PENDING')], default='1', max_length=15),
        ),
    ]
