# Generated by Django 4.2 on 2023-04-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_delivery_requirements_customer_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_details', models.CharField(max_length=100)),
                ('Role', models.CharField(choices=[('1', 'DRIVER'), ('2', 'LABOUR'), ('3', 'SUPPLIYER'), ('4', 'OTHER')], default='4', max_length=15)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
