# Generated by Django 4.2 on 2023-04-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_contact_detail_contact_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Details',
            new_name='Contact_Detail',
        ),
    ]
