# Generated by Django 4.2 on 2023-04-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
