# Generated by Django 4.2 on 2023-04-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agreement_file',
            field=models.FileField(blank=True, null=True, upload_to='media/agreements/'),
        ),
    ]
